version: 2.1
orbs:
  node: circleci/node@6.1.0

jobs:
  setup:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}-{{ checksum "client/package-lock.json" }}-{{ checksum "server/package-lock.json" }}
      - run:
          name: Install project dependencies
          command: npm run ci-all
      - save_cache:
          paths:
            - ~/.npm
          key: npm-packages-{{ checksum "package-lock.json" }}-{{ checksum "client/package-lock.json" }}-{{ checksum "server/package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run ESLint
          command: npx eslint . --config .eslintrc.json || true
      - run:
          name: Run tests
          command: npm test --prefix client

  build:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build client
          command: npm run build --prefix client
      - run:
          name: Build server
          command: npm run build --prefix server
      - persist_to_workspace:
          root: .
          paths:
            - client/build
            - server/dist
            - server/package.json
            - server/package-lock.json

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - add_ssh_keys:
          fingerprints:
            - "SHA256:6+qHFQDbqCYFzFzHfY7fpBaly2rEB83DUxswOGj6dkI"
      - run:
          name: Setup and Debug Environment
          command: |
            # Unset any old variables that might be interfering
            unset DEPLOY_PATH
            
            # Export necessary variables
            echo 'export SSH_USER=${SSH_USER}' >> "$BASH_ENV"
            echo 'export SSH_HOST=${SSH_HOST}' >> "$BASH_ENV"
            
            # Source the Bash environment
            source "$BASH_ENV"
            
            # Debug prints (safe parts only)
            echo "SSH_USER is set: $(if [ -n "$SSH_USER" ]; then echo "Yes"; else echo "No"; fi)"
            echo "SSH_HOST is set: $(if [ -n "$SSH_HOST" ]; then echo "Yes"; else echo "No"; fi)"
            echo "Destination path: /var/www/minecraft-skin-merger"
      - run:
          name: Deploy to Server
          command: |
            # Source the Bash environment
            source "$BASH_ENV"
            
            # Deploy client build files
            echo "Deploying client build files..."
            scp -r -o StrictHostKeyChecking=no /home/circleci/project/client/build/* $SSH_USER@$SSH_HOST:/var/www/minecraft-skin-merger/client
            
            # Debug: Verify client deployment
            echo "Verifying client files on the server..."
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "ls -la /var/www/minecraft-skin-merger/client || echo 'Client files deployment failed'"
            
            # Deploy server files and package.json
            echo "Deploying server files and package.json..."
            scp -r -o StrictHostKeyChecking=no /home/circleci/project/server/dist/* /home/circleci/project/server/package*.json $SSH_USER@$SSH_HOST:/var/www/minecraft-skin-merger/server
            
            # Debug: Verify server deployment 
            echo "Verifying server files on the server..."
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "ls -la /var/www/minecraft-skin-merger/server || echo 'Server files deployment failed'"
            
            # Connect via SSH, install production dependencies, restart PM2 and Nginx
            echo "Installing dependencies and restarting services..."
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST \<< EOF
              cd /var/www/minecraft-skin-merger/server
              echo "Installing npm production dependencies..."
              npm install --production || echo "npm install failed"
              echo "Restarting PM2..."
              pm2 restart /var/www/minecraft-skin-merger/ecosystem.config.js || echo "PM2 restart failed"
              echo "Restarting Nginx..."
              sudo systemctl restart nginx || echo "Nginx restart failed"
            EOF



workflows:
  setup-test-build-deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master