version: 2.1
orbs:
  node: circleci/node@6.1.0

jobs:
  setup:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install project dependencies
          command: npm run install-all
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run ESLint
          command: npx eslint . --config .eslintrc.json || true
      - run:
          name: Run tests
          command: npm test

  build:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build client
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "SHA256:6+qHFQDbqCYFzFzHfY7fpBaly2rEB83DUxswOGj6dkI"
      - run:
          name: Deploy to server
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST '
              mkdir -p $DEPLOY_PATH &&
              rm -rf $DEPLOY_PATH/* &&
              exit
            '
            scp -r ./* $SSH_USER@$SSH_HOST:$DEPLOY_PATH
            ssh $SSH_USER@$SSH_HOST '
              cd $DEPLOY_PATH &&
              npm install --production &&
              pm2 restart minecraft-skin-merger
            '

workflows:
  version: 2
  setup-test-build-deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master