version: 2.1
orbs:
  node: circleci/node@6.1.0

jobs:
  setup:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}-{{ checksum "client/package-lock.json" }}-{{ checksum "server/package-lock.json" }}
      - run:
          name: Install project dependencies
          command: npm run ci-all
      - save_cache:
          paths:
            - ~/.npm
          key: npm-packages-{{ checksum "package-lock.json" }}-{{ checksum "client/package-lock.json" }}-{{ checksum "server/package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run ESLint
          command: npx eslint . --config .eslintrc.json || true
      - run:
          name: Run tests
          command: npm test --prefix client

  build:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build client
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - client/build
            - server/dist
            - server/package.json
            - server/package-lock.json

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - add_ssh_keys:
          fingerprints:
            - "SHA256:6+qHFQDbqCYFzFzHfY7fpBaly2rEB83DUxswOGj6dkI"
      - run:
          name: Deploy to Server
          command: |
            # Deploy client build files
            scp -vr /home/circleci/project/client/build/* 
                    $SSH_USER@$SSH_HOST:/var/www/minecraft-skin-merger/client
            # Deploy server files and package.json
            scp -vr /home/circleci/project/server/dist/* \
                    /home/circleci/project/server/package*.json \
                    $SSH_USER@$SSH_HOST:/var/www/minecraft-skin-merger/server
            # Connect via SSH, install production dependencies, restart PM2 and Nginx
            ssh -v $SSH_USER@$SSH_HOST \<< EOF
              cd /var/www/minecraft-skin-merger/server
              npm install --production
              pm2 restart /var/www/minecraft-skin-merger/ecosystem.config.js
              sudo systemctl restart nginx
            EOF

workflows:
  setup-test-build-deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master